Fix build: Remove unused variable
This fixes:

back (most recent call last):
  File "tools/netsim/scripts/build_tools.py", line 157, in <module>
  main()
    File "tools/netsim/scripts/build_tools.py", line 119, in main
    cmd = cmd + ["--crash", "prod"]
    UnboundLocalError: local variable 'cmd' referenced before
    assignmentPlease enter the commit message for your changes. Lines starting

Change-Id: Ie8e2cb3d1e7faef1e21f2ab0f38935b8627891bd