Add -Wno-missing-field-initializers to generic_flags
Both C and C++ files can have spurious warnings due to this.

Getting errors like:
```
trusty/user/base/app/apploader/package_tool/../app_manifest_parser.cpp:45:5: error: missing field 'uuid' initializer [-Werror,-Wmissing-designated-field-initializers]
   45 |     };
      |     ^
1 error generated.

Change-Id: I2c344a9f5f7a56603da43dede968ff6034b8f4e3