ANDROID: Remove .patch duplicating copy_out
Otherwise, this causes cargo_embargo to fail with

  ERROR: failed to apply patch "power_monitor/patches/Android.bp.patch"
  thread 'main' panicked at development/tools/cargo_embargo/src/main.rs:426:9:

with the underlying 'patch' command failing with

  Reversed (or previously applied) patch detected!  Assume -R? [n]
  Apply anyway? [n]
  2 out of 2 hunks ignored -- saving rejects to file
  ${ANDROID_BUILD_TOP}/external/crosvm/power_monitor/Android.bp.rej

and copy_out seems to already be generating the same blueprint code.

Test: export CC="${ANDROID_BUILD_TOP}/prebuilts/clang/host/linux-x86/clang-r536225/bin/clang"
Test: cargo_embargo generate cargo_embargo.json
Change-Id: I30620e13a0d9a3cabbaee6fa671c852c49ce6f56