Make GoogleLoginStateTest run again
I9159b8b3f7acb added an Objects.requireNotNull which mockito
doesn't seem to like. This results in GoogleLoginStateTest failing
with:

MockitoException: Cannot instrument class com.google.gct.login.GoogleLoginState \
  because it or one of its supertypes could not be initialized

This wasn't caught earlier because the tests in this module
are not being run in presubmit.

Bug: 279338486
Test: GoogleLoginStateTest passes again
Change-Id: Ib001a05a6960f28ee74b4a0f0c3b5d4103f7b09c