Add "java/dagger/hilt/android/lifecycle/*.kt" to dagger2's hilt_android
https://cs.android.com/android/platform/superproject/main/+/main:external/dagger2/java/dagger/hilt/android/lifecycle/HiltViewModelExtensions.kt
is missing. This was discovered because another aosp app uses assisted
injection, which requires HiltViewModelExtensions. Without this, a
runtime NoClassDefFoundError is thrown.

Bug: 344038824
Test: The app does not have runtime error anymore
Change-Id: I1675f767ce8d1bf6e987c9e93908ffbf21aceb3e