Autoupdate of 2 submodules
*frameworks/proto_logging updated to d5600d6deca66135d8d0d4ab979b86bb23e20492
DO NOT MERGE ANYWHERE: Update Health Connect Atoms to match latest main.

Host in the CtsHealthConnectHostTestCases is running the tests from outdated protos which is causing NoSuchMethodError Error. For example:
java.lang.NoSuchMethodError: 'boolean com.android.os.healthfitness.api.HealthConnectUsageStats.getIsMonthlyActiveUser()' at android.healthconnect.cts.logging.HealthConnectDailyLogsStatsTests.testIsUserActive_insertRecord_userMonthlyActiveNextDay(HealthConnectDailyLogsStatsTests.java:163)

Test: atest
Bug: 358006651
Change-Id: I8fb98a0edfa5201863fb690de68117648371a907

*packages/modules/HealthFitness updated to 1f7674a413bfc774ed327e8b6e44da12d7278424
DO NOT MERGE ANYWHERE: Add placeholder package to match updated atom.

Given this code will be never be called adding a placeholder package name for logging should not cause any issues in production.

Test: atest
Bug: 358006651
Change-Id: I657485efc7b506f5b885f8c9940c6dd2b8da9a93