Update needed for Rust v1.77.0
error: non-binding let on a synchronization lock
   --> packages/modules/Virtualization/virtualizationmanager/src/crosvm.rs:418:14
    |
418 |         let (_, result) = self
    |              ^ this lock is not assigned to a binding and is immediately dropped
    |
    = help: consider immediately dropping the value using `drop(..)` after the `let` statement
    = note: `#[deny(let_underscore_lock)]` on by default
help: consider binding to an unused variable to avoid immediately dropping the value
    |
418 |         let (_unused, result) = self
    |              ~~~~~~~

error: aborting due to 1 previous error

Bug: 330185853
Test: ./test_compiler.py --prebuilt-path dist/rust-dev.tar.xz  --target aosp_cf_x86_64_phone --image
Change-Id: Ib0116e7bb6999734ed208b72f0c3ed68411ba4bf