Pass output file argument to guice_munge instead of redirecting.
It looks like a recent change to the JDK has caused logs to be written
to stdout intermittently, causing errors such as the following when
compiling a source file processed by guice_munge:

out.cfa64l5/soong/.intermediates/external/guice/guice/linux_glibc_common/javac/srcjars/external/guice/core/src/com/google/inject/internal/InternalProviderInstanceBindingImpl.java:1: error: class, interface, enum, or record expected
[0.003s][warning][perf,memops] Cannot use file /tmp/hsperfdata_nobody/75537 because it is locked by another process (errno = 11)
^

Avoid the problem by passing an output file argument to guice_munge
instead of redirecting stdout to the output file.

Bug: 330410989
Change-Id: I218f9b8597b77350e810d1bfcfa60fe94312c876