Fix build with clang-r563880
system/keymaster/include/keymaster/contexts/soft_keymaster_context.h:70:28: error: virtual function 'GetSupportedAlgorithms' has a different return type ('keymaster_algorithm_t *') than the function it overrides
 (which has return type 'const keymaster_algorithm_t *')
   70 |     keymaster_algorithm_t* GetSupportedAlgorithms(size_t* algorithms_count) const override;
      |     ~~~~~~~~~~~~~~~~~~~~~~ ^
system/keymaster/include/keymaster/keymaster_context.h:108:42: note: overridden virtual function is here
  108 |     virtual const keymaster_algorithm_t* GetSupportedAlgorithms(size_t* algorithms_count) const = 0;
      |                   ~~~~~~~~~~~~~~~~~~~~~~ ^

Test: presubmit
Bug: 401330760
Change-Id: I234a84b9acceb34c05834e0cb7427d98d9ef64a3