Update git submodules
* Update external/dokka from branch 'master'
  to 940d3841dee22910c65115a59ae68922747c5782
  - Augmenting "Not implemented mainUri" error to describe the node in question
    
    Now instead of saying
    
      java.lang.AssertionError: Not implemented mainUri for TypeAlias
    
    , the error says
    
      java.lang.AssertionError: Not implemented mainUri for TypeAlias (TypeAlias:GuardedBy)
    
    Bug: 154755010
    Test: cd ../../frameworks/support/ui && BUILD_DOKKA=true ./gradlew dokkaKotlinTipOfTreeDocs # and see that the error message is changed like above
    Change-Id: Iefbeaa66de7e7b2ef1c7b870067f143847c831f7