minigbm: Enable use in cros_codecs
Previous to this CL, cros_codecs caused a build failure in soong
with the following message:
error: system/cros-codecs/Android.bp:17:1: module "libcros_codecs"
variant "android_arm64_armv8-2a_cortex-a55_rlib_rlib-std": depends
on //external/minigbm:libgbm_sys which is not visible to this module
You may need to add "//system/cros-codecs" to its visibility

This CL updates libgbm_sys's visibility with cros_codecs.

Bug: 389780527
Test: Build cros_codecs with libgbm_sys as a depedency.
Change-Id: Id4538880193adfda55d755449d1984d83b0a6919