Change phone required for screenshot tests.
If Pixel 2 is used, it fails with:
```
java.lang.AssertionError: Sizes are different! Expected: [1080, 2400], Actual: [1080, 1920]
```

PiperOrigin-RevId: 800067250
Change-Id: I582c0ff63362a526d1ec92b3e89f5b520cb101d8