Autoupdate of 3 submodules
*build/soong updated to 6edbaa369fb97a27f321ac2e397937e0aabe2766
Merge "Remove wtautological warnings added during toolchain update" into main
*external/cblas updated to b30ccf3bbdb5adcafebdc3671567fe4b36752996
Add "-Wno-tautological-negation-compare"

Silences the compiler warning:
```
FAILED: out/soong/.intermediates/external/cblas/libblas/android_x86_64_silvermont_shared/obj/external/cblas/src/cblas_xerbla.o
...ared/obj/external/cblas/src/cblas_xerbla.o.d -o out/soong/.intermediates/external/cblas/libblas/android_x86_64_silvermont_shared/obj/external/cblas/src/cblas_xerbla.o external/cblas/src/cblas_xerbla.c
external/cblas/src/cblas_xerbla.c:65:13: error: '&&' of a value and its negation always evaluates to false [-Werror,-Wtautological-negation-compare]
   65 |    if (info && !info)
      |        ~~~~~^~~~~~~~
1 error generated.
```

Bug: b/301328082
Change-Id: I7189433826561089f64837ef0b6b4b2267a829ec

*external/icu updated to 449c160c882ebb69c6e78c33d5558ee0f0928930
Merge "Add "-Wno-tautological-negation-compare"" into main