Set `-C panic=abort` for libpanic_abort.rust-sysroot
Linking against libpanic_abort.rust-sysroot fails if it was not built
with `-C panic=abort`:
error: the crate `panic_abort` does not have the panic strategy `abort`

The libpanic_abort.rust_sysroot is normally used on the device, where
the global rust flags have `-C panic=abort`.  However, it can get used
on the host when compiling against musl (which unlike glibc targets
uses a locally built sysroot instead of a prebuilt sysroot), and when
`-C panic=abort` is manually specified in a module's rust flags (which
is required for tests that use crate::inherited_fd::test).

Add `-C panic=abort` to `libpanic_abort.rust-sysroot` to make sure it
has the right flags even when compiled for targets that don't default
to panic=abort.

Bug: 367345629
Test: lunch aosp_cf_arm64_phone-trunk_staging-userdebug && m out/soong/.intermediates/system/librustutils/librustutils_test/linux_musl_arm64/librustutils_test.clippy
Flag: EXEMPT bugfix
Change-Id: I938e070f11df8f70c9b026e4601d76f8a52ea06e