Autoupdate of 2 submodules
*tools/adt/idea updated to ac7e76aa8f5e723d4198d01d7b957b71483cba56
Delete NativeLibrary constructor

Bug: n/a
Test: SourceFoldersTest
Change-Id: Iac8f4b078d1d0e744bf41b49c0a91b8b2832c961

*tools/vendor/google updated to 6400bf0f602ca9e0c1492665635004972eab54c3
Use orElse, rather than orElseGet

As suggested by ErrorProne check:

error: [DangerousLiteralNull] This method is null-hostile: passing a null literal to it is always wrong
  NativeLibrary nativeLibAfterReload = libraries.stream().filter((library) -> library.name.equals("libnative-lib.so")).findAny().orElseGet(null);
(see https://errorprone.info/bugpattern/DangerousLiteralNull)
  Did you mean 'NativeLibrary nativeLibAfterReload = libraries.stream().filter((library) -> library.name.equals("libnative-lib.so")).findAny().orElse(null);'?

Bug: n/a
Test: ApkReloaderIntegrationTest
Change-Id: If2345ddfa03b1b9054432525cd5fb5a06ad463f3